version: '3'
services:

  docker-accumulo:
    image: docker-accumulo-muse:latest
    hostname: docker-accumulo

    # this will pull in data on start
    volumes:
     - ./data:/ingest

    ports:
      - 8042:8042
      - 8088:8088
      - 19888:19888
      - 50010:50010
      - 50020:50020
      - 50070:50070
      - 50075:50075
      - 50090:50090
      - 9995:9995
      - 9999:9999
      - 8052:8052

volumes:
  data:
